apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment-remote
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: image_processor
        image: sam7933715/image_processor
        ports:
        - containerPort: 1883
